blueprint:
  name: Apply Adaptive Lighting
  description: >
    Triggers whenever the selected light(s) or light group turn on
    (e.g., via physical Hue wall switch) and applies the current
    Adaptive Lighting settings after a brief delay to ensure the light
    is fully responsive. Includes safeguards against race conditions
    and unnecessary triggers.
  domain: automation
  version: 2.0.0
  input:
    light_entity:
      name: Light or Light Group
      description: The light entity or group that is controlled by your physical switch.
      selector:
        entity:
          domain: light
          multiple: true

    adaptive_lighting_switch:
      name: Adaptive Lighting Switch
      description: The Adaptive Lighting switch entity (e.g., switch.adaptive_lighting_living_room).
      selector:
        entity:
          domain: switch

    apply_delay:
      name: Application Delay
      description: Delay (in seconds) before applying adaptive lighting. Prevents race conditions with slow-responding lights.
      default: 0.5
      selector:
        number:
          min: 0
          max: 5
          step: 0.1
          unit_of_measurement: seconds
          mode: slider

    transition:
      name: Transition Time (Optional)
      description: Transition time in seconds for applying adaptive lighting. Leave at 0 for instant change.
      default: 0
      selector:
        number:
          min: 0
          max: 10
          step: 0.5
          unit_of_measurement: seconds
          mode: slider

    prefer_rgb_color:
      name: Prefer RGB Color
      description: Whether to prefer RGB color adjustment over color temperature when possible.
      default: false
      selector:
        boolean:

variables:
  transition_time: !input transition
  prefer_rgb: !input prefer_rgb_color

trigger:
  - platform: state
    entity_id: !input light_entity
    from: "off"
    to: "on"

condition:
  # Only apply if adaptive lighting switch is on AND available
  - condition: state
    entity_id: !input adaptive_lighting_switch
    state: "on"
  # Ensure the light is actually on (guard against race conditions)
  - condition: state
    entity_id: !input light_entity
    state: "on"

action:
  # Small delay to ensure light is fully responsive
  - delay:
      seconds: !input apply_delay

  # Apply adaptive lighting with optional parameters
  - service: adaptive_lighting.apply
    target:
      entity_id: !input adaptive_lighting_switch
    data:
      entity_id: !input light_entity
      transition: "{{ transition_time }}"
      prefer_rgb_color: "{{ prefer_rgb }}"

mode: single
max_exceeded: silent
