blueprint:
  name: Auto‑Off Lights when Occupancy Ends (Area)
  description: >
    Turn off all lights in a selected area when an occupancy sensor changes to a specified state.
    Optional: wait duration (for), optional enable/disable input_boolean and transition time.
  domain: automation
  input:
    occupancy_sensor:
      name: Occupancy sensor
      selector:
        entity:
          domain: binary_sensor
    from_state:
      name: From state (optional filter)
      description: "Only trigger when the sensor changed from this state. Leave as 'on' to match your original automation."
      default: "on"
      selector:
        text:
    to_state:
      name: To state
      description: "State to trigger on (e.g. 'off' / 'unoccupied')."
      default: "off"
      selector:
        text:
    wait_for:
      name: Wait duration
      description: "How long the occupancy sensor must stay in the target state before turning lights off."
      default: "00:10:00"
      selector:
        duration: {}
    target_area:
      name: Area to turn off lights
      selector:
        area: {}
    enable_boolean:
      name: Enable input_boolean (optional)
      description: "If set, the automation only runs when this input_boolean is in the required state. Leave blank to disable this check."
      selector:
        entity:
          domain: input_boolean
    enable_state:
      name: Required state of enable input_boolean
      default: "on"
      selector:
        text:
    transition:
      name: Transition (seconds)
      description: "Transition time in seconds when turning lights off."
      default: 5
      selector:
        number:
          min: 0
          max: 300
          unit_of_measurement: seconds

trigger:
  - platform: state
    entity_id: !input occupancy_sensor
    from: !input from_state
    to: !input to_state
    for: !input wait_for

condition:
  - condition: template
    # If no enable_boolean provided, this evaluates to true.
    value_template: >-
      {% if not ( !input enable_boolean ) %}
        true
      {% else %}
        {{ is_state( !input enable_boolean, !input enable_state ) }}
      {% endif %}

action:
  - service: light.turn_off
    target:
      area_id: !input target_area
    data:
      transition: !input transition
mode: single
