blueprint:
  name: Auto Light (Occupancy + Brightness)
  description: >
    Automatically turns lights on/off based on occupancy and indoor brightness.
    Uses hysteresis (different on/off thresholds) to prevent flickering.
    Configurable off-delay prevents lights from turning off immediately when motion stops.
  domain: automation
  input:
    occupancy_sensor:
      name: Occupancy Sensor
      description: Binary sensor that detects presence/motion (e.g., binary_sensor.detection_area_studio_occupancy_status)
      selector:
        entity:
          domain: binary_sensor

    lights:
      name: Lights
      description: The lights to control (supports entities, devices, areas, or labels)
      selector:
        target:
          entity:
            domain: light

    auto_on_enabled:
      name: Enable Auto ON
      description: Automatically turn lights on when occupancy is detected and brightness is low
      default: true
      selector:
        boolean:

    auto_off_enabled:
      name: Enable Auto OFF
      description: Automatically turn lights off when no occupancy or brightness is high
      default: true
      selector:
        boolean:

    sleep_mode_entity:
      name: Sleep Mode (optional)
      description: Input boolean for sleep mode - when ON, lights will only turn OFF automatically, never ON
      default: sun.sun
      selector:
        entity:
          domain: input_boolean

    presence_mode_entity:
      name: Presence Mode (optional)
      description: Input boolean for presence - when ON (present), lights can turn on automatically. When OFF (away), lights only turn OFF, never ON
      default: sun.sun
      selector:
        entity:
          domain: input_boolean

    lux_sensor:
      name: Indoor Lux Sensor
      description: Sensor measuring indoor illuminance in lux
      default: sun.sun
      selector:
        entity:
          domain: sensor

    lux_threshold_on:
      name: Turn ON Below (lux)
      description: Turn on lights when brightness is below this value
      default: 50
      selector:
        number:
          min: 0
          max: 1000
          step: 5
          unit_of_measurement: lx
          mode: slider

    lux_threshold_off:
      name: Turn OFF Above (lux)
      description: Turn off lights when brightness exceeds this value (should be higher than ON threshold to prevent flickering)
      default: 100
      selector:
        number:
          min: 0
          max: 1000
          step: 5
          unit_of_measurement: lx
          mode: slider

    off_delay:
      name: Turn OFF Delay
      description: Wait this many seconds after motion stops before turning off lights (0 = immediate)
      default: 0
      selector:
        number:
          min: 0
          max: 900
          step: 30
          unit_of_measurement: seconds
          mode: slider

variables:
  auto_on_enabled: !input auto_on_enabled
  auto_off_enabled: !input auto_off_enabled
  sleep_mode_entity: !input sleep_mode_entity
  presence_mode_entity: !input presence_mode_entity
  lux_sensor: !input lux_sensor
  lux_on: !input lux_threshold_on
  lux_off: !input lux_threshold_off
  off_delay: !input off_delay

  # Check if sleep mode is active
  sleep_mode_active: >
    {{ sleep_mode_entity != 'sun.sun' and is_state(sleep_mode_entity, 'on') }}

  # Check if presence mode allows auto-on (not configured OR present)
  presence_allows_on: >
    {{ presence_mode_entity == 'sun.sun' or is_state(presence_mode_entity, 'on') }}

  # Compute whether brightness is low (lights should be on)
  brightness_is_low: >
    {% if lux_sensor != '' and lux_sensor != 'sun.sun' %}
      {{ states(lux_sensor) | float(1000) < lux_on }}
    {% else %}
      false
    {% endif %}

  # Compute whether brightness is high (lights can be turned off)
  brightness_is_high: >
    {% if lux_sensor != '' and lux_sensor != 'sun.sun' %}
      {{ states(lux_sensor) | float(0) > lux_off }}
    {% else %}
      false
    {% endif %}

trigger:
  # Trigger when occupancy changes
  - platform: state
    entity_id: !input occupancy_sensor
    from: "off"
    to: "on"
    id: motion_detected
  - platform: state
    entity_id: !input occupancy_sensor
    from: "on"
    to: "off"
    id: motion_cleared

  # Trigger when lux sensor changes
  - platform: state
    entity_id: !input lux_sensor
    id: lux_changed

action:
  - choose:
      # Turn ON: auto-on enabled AND occupancy detected AND brightness is low AND NOT sleeping AND present
      - conditions:
          - condition: template
            value_template: "{{ auto_on_enabled }}"
          - condition: template
            value_template: "{{ not sleep_mode_active }}"
          - condition: template
            value_template: "{{ presence_allows_on }}"
          - condition: state
            entity_id: !input occupancy_sensor
            state: "on"
          - condition: template
            value_template: "{{ brightness_is_low }}"
        sequence:
          - service: light.turn_on
            target: !input lights

      # Turn OFF: auto-off enabled AND (no occupancy OR brightness is high)
      - conditions:
          - condition: template
            value_template: "{{ auto_off_enabled }}"
          - condition: or
            conditions:
              - condition: state
                entity_id: !input occupancy_sensor
                state: "off"
              - condition: template
                value_template: "{{ brightness_is_high }}"
        sequence:
          - if:
              - condition: template
                value_template: "{{ off_delay | int > 0 }}"
            then:
              - delay:
                  seconds: "{{ off_delay | int }}"
          - service: light.turn_off
            target: !input lights

mode: restart
max_exceeded: silent
