blueprint:
  name: Auto Arm/Disarm Alarm (Alarmo)
  description: >
    Automatically arms the alarm when all tracked persons are away for a configurable duration.
    Automatically disarms when one person returns home for a configurable duration.
    Designed for use with the Alarmo integration.
    Robust handling of edge cases and state transitions.
  domain: automation
  input:
    persons:
      name: Persons to Track
      description: Select all persons to track for presence. All must be away to arm, any one home to disarm.
      selector:
        entity:
          domain: person
          multiple: true

    alarm_panel:
      name: Alarm Control Panel
      description: The Alarmo alarm control panel entity
      selector:
        entity:
          domain: alarm_control_panel

    away_delay:
      name: Away Delay (Minutes)
      description: Number of minutes both persons must be away before arming
      default: 5
      selector:
        number:
          min: 0
          max: 60
          step: 1
          unit_of_measurement: minutes
          mode: slider

    home_delay:
      name: Home Delay (Minutes)
      description: Number of minutes a person must be home before disarming
      default: 2
      selector:
        number:
          min: 0
          max: 30
          step: 1
          unit_of_measurement: minutes
          mode: slider

    alarm_code:
      name: Alarm Code (optional)
      description: Code to arm/disarm the alarm (leave empty if not required)
      default: ""
      selector:
        text:
          type: password

variables:
  persons: !input persons
  alarm_panel: !input alarm_panel
  alarm_code: !input alarm_code
  away_delay_min: !input away_delay
  home_delay_min: !input home_delay

  # Check if ALL persons are away (not_home)
  all_away: >
    {% set person_list = persons if persons is iterable and persons is not string else [persons] %}
    {{ person_list | map('states') | select('eq', 'not_home') | list | length == person_list | length }}

  # Check if at least one person is home
  someone_home: >
    {% set person_list = persons if persons is iterable and persons is not string else [persons] %}
    {{ person_list | map('states') | select('eq', 'home') | list | length > 0 }}

  # Check if alarm is currently disarmed
  alarm_disarmed: >
    {{ is_state(alarm_panel, 'disarmed') }}

  # Check if alarm is currently armed or in arming/pending state
  alarm_armed_or_arming: >
    {{ states(alarm_panel) in ['armed_away', 'armed_home', 'armed_night', 'armed_vacation', 'arming', 'pending'] }}

  # Check alarm availability
  alarm_available: >
    {{ states(alarm_panel) not in ['unknown', 'unavailable'] }}

trigger_variables:
  _away_delay: !input away_delay
  _home_delay: !input home_delay

trigger:
  # Any person state changes - we'll filter in conditions
  - platform: state
    entity_id: !input persons
    to: "not_home"
    for:
      minutes: "{{ _away_delay | int }}"
    id: person_away

  - platform: state
    entity_id: !input persons
    to: "home"
    for:
      minutes: "{{ _home_delay | int }}"
    id: person_home

  # Also trigger when alarm state changes to handle edge cases
  - platform: state
    entity_id: !input alarm_panel
    id: alarm_state_changed

condition:
  # Only proceed if alarm is available
  - condition: template
    value_template: "{{ alarm_available }}"

action:
  - choose:
      # ARM: All persons have been away for the configured delay and alarm is disarmed
      - conditions:
          - condition: trigger
            id:
              - person_away
          - condition: template
            value_template: "{{ all_away }}"
          - condition: template
            value_template: "{{ alarm_disarmed }}"
        sequence:
          # Double-check all persons are still away before arming
          - condition: template
            value_template: "{{ all_away }}"
          - service: alarm_control_panel.alarm_arm_away
            target:
              entity_id: !input alarm_panel
            data:
              code: "{{ alarm_code if alarm_code != '' else none }}"

      # DISARM: At least one person has been home for the configured delay and alarm is armed/arming
      - conditions:
          - condition: trigger
            id:
              - person_home
          - condition: template
            value_template: "{{ someone_home }}"
          - condition: template
            value_template: "{{ alarm_armed_or_arming }}"
        sequence:
          # Double-check someone is still home before disarming
          - condition: template
            value_template: "{{ someone_home }}"
          - service: alarm_control_panel.alarm_disarm
            target:
              entity_id: !input alarm_panel
            data:
              code: "{{ alarm_code if alarm_code != '' else none }}"

      # RECOVERY: If alarm state changed externally and is out of sync, try to correct
      # e.g., if someone is home but alarm is armed, disarm it
      - conditions:
          - condition: trigger
            id: alarm_state_changed
          - condition: template
            value_template: "{{ someone_home and alarm_armed_or_arming }}"
        sequence:
          - delay:
              seconds: 5
          # Re-check conditions after brief delay
          - condition: template
            value_template: "{{ someone_home and alarm_armed_or_arming }}"
          - service: alarm_control_panel.alarm_disarm
            target:
              entity_id: !input alarm_panel
            data:
              code: "{{ alarm_code if alarm_code != '' else none }}"

mode: parallel
max_exceeded: silent
