blueprint:
  name: Auto Light Off (Motion + Brightness)
  description: Turns off lights in an area when no motion is detected OR when the brightness exceeds the set threshold.
  domain: automation
  input:
    occupancy_sensor:
      name: Occupancy Sensor
      description: The binary sensor that detects presence/motion (e.g., binary_sensor.detection_area_studio_occupancy_status)
      selector:
        entity:
          domain: binary_sensor
    lux_sensor:
      name: Brightness Sensor
      description: The sensor measuring illuminance in lux (e.g., sensor.hue_motion_sensor_1_beleuchtungsstarke_3)
      selector:
        entity:
          domain: sensor
    threshold_helper:
      name: Brightness Threshold (deprecated)
      description: Input number defining the lux threshold above which lights can be turned off (e.g., input_number.leuchten_helligkeit_grenzwert)
      selector:
        entity:
          domain: input_number
    light_area:
      name: Light Area
      description: The area where the lights should be turned off (e.g., studio)
      selector:
        area:

trigger:
  - platform: state
    entity_id: !input occupancy_sensor
    from: "on"
    to: "off"
  - platform: state
    entity_id: !input lux_sensor

condition:
  - condition: state
    entity_id: !input occupancy_sensor
    state: "off"

action:
  - service: light.turn_off
    target:
      area_id: !input light_area

mode: single
